---
apiVersion: v1
kind: LimitRange
metadata:
  name: admission-resources
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 256Mi
      defaultRequest:
        memory: 64Mi
        cpu: 20m
      min:
        cpu: 1m
        memory: 1Mi
      max:
        memory: 4Gi
        cpu: 1000m
      maxLimitRequestRatio:
        cpu: 100
        memory: 100
    - type: Pod
      min:
        cpu: 1m
        memory: 1Mi
      max:
        memory: 4Gi
        cpu: 1000m
